---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by KIPKIPS.
--- DateTime: 2021/9/3 16:41
---
local config = require("library")
--print(config.nickHeader)

local getNickHeader = function()
    math.randomseed(tostring(os.time()):reverse():sub(1,7))
    return config.nickHeader[math.random(0,329)];
end

local getNickFoot = function()
    math.randomseed(tostring(os.time()):reverse():sub(1,7))
    return config.nickFoot[math.random(0,331)];
end

local getNickName = function()
    return getNickHeader()..getNickFoot()
end

print(getNickName())
